version: '3.9'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_hebrew_production
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

volumes:
  postgres_data:
