version: '3.9'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_hebrew_development
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/dev
    env_file:
      - .env
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stop_grace_period: 0s

volumes:
  postgres_data:
