apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-hebrew-app
  namespace: learning-hebrew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-hebrew-app
  template:
    metadata:
      labels:
        app: learning-hebrew-app
    spec:
      initContainers:
      - name: db-migrate
        image: learning-hebrew:local
        imagePullPolicy: Never  # Use local image
        command: ["bin/rails", "db:migrate", "db:seed"]
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
      containers:
      - name: rails-app
        image: learning-hebrew:local
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: learning-hebrew-service
  namespace: learning-hebrew
spec:
  selector:
    app: learning-hebrew-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP