apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: learning-hebrew
type: Opaque
data:
  # postgres-user: "postgres" base64 encoded
  postgres-user: cG9zdGdyZXM=
  # postgres-password: "password" base64 encoded (simple for local)
  postgres-password: cGFzc3dvcmQ=