apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-hebrew-app
  namespace: learning-hebrew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-hebrew-app
  template:
    metadata:
      labels:
        app: learning-hebrew-app
    spec:
      initContainers:
      - name: db-migrate
        image: learning-hebrew:latest
        imagePullPolicy: Never
        command: ["bin/rails", "db:migrate", "db:seed"]
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: DATABASE_NAME
          value: "learning_hebrew_development"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rails-master-key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key-base
        # Build/deployment info
        - name: GIT_SHA
          value: "unknown"
        - name: BUILD_NUMBER
          value: "unknown"
        - name: DEPLOYED_AT
          value: "unknown"
        - name: IMAGE_TAG
          value: "latest"
      containers:
      - name: rails-app
        image: learning-hebrew:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: DATABASE_NAME
          value: "learning_hebrew_development"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rails-master-key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key-base
        # Build/deployment info
        - name: GIT_SHA
          value: "unknown"
        - name: BUILD_NUMBER
          value: "unknown"
        - name: DEPLOYED_AT
          value: "unknown"
        - name: IMAGE_TAG
          value: "latest"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: learning-hebrew-service
  namespace: learning-hebrew
spec:
  selector:
    app: learning-hebrew-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP