apiVersion: v1
kind: SecretProviderClass
metadata:
  name: app-secrets-spc
  namespace: learning-hebrew
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/learning-hebrew-1758491674/secrets/postgres-user/versions/latest"
        path: "postgres-user"
      - resourceName: "projects/learning-hebrew-1758491674/secrets/postgres-password/versions/latest"
        path: "postgres-password"
      - resourceName: "projects/learning-hebrew-1758491674/secrets/rails-master-key/versions/latest"
        path: "rails-master-key"
      - resourceName: "projects/learning-hebrew-1758491674/secrets/secret-key-base/versions/latest"
        path: "secret-key-base"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: learning-hebrew
type: Opaque
data:
  # These will be populated by the CSI driver from Google Secret Manager
  # No actual secret values stored in git!